"""
Ingest a Bilibili VOD (video-on-demand) by URL.

Downloads both the video (via yt-dlp) and danmaku XML
(via Bilibili public comment API).
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import tempfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Callable, Optional
from urllib.parse import urlparse

import httpx

from ..danmaku.models import DanmakuComment
from ..danmaku.parser import parse_xml
from ..logging import console
from ..utils import parse_bool, safe_decode
from .ytdlp_guard import ensure_ytdlp_ready
from .base import IngestResult
from .local import _probe_duration

_BILI_VIEW_API = "https://api.bilibili.com/x/web-interface/view"
_BILI_DANMAKU_URL = "https://comment.bilibili.com/{cid}.xml"
_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    ),
    "Referer": "https://www.bilibili.com",
}


def _bili_cookie_dict_from_env() -> dict[str, str]:
    cookies = {}
    sessdata = str(os.getenv("BILI_SESSDATA", "") or "").strip()
    bili_jct = str(os.getenv("BILI_BILI_JCT", "") or "").strip()
    buvid3 = str(os.getenv("BILI_BUVID3", "") or "").strip()
    if sessdata:
        cookies["SESSDATA"] = sessdata
    if bili_jct:
        cookies["bili_jct"] = bili_jct
    if buvid3:
        cookies["buvid3"] = buvid3
    return cookies


def _write_netscape_cookie_file(cookie_path: Path, cookies: dict[str, str]) -> Path:
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file is generated by Stream Clipper for yt-dlp.",
    ]
    for name, value in cookies.items():
        if not value:
            continue
        lines.append("\t".join([
            ".bilibili.com",
            "TRUE",
            "/",
            "TRUE",
            "2147483647",
            name,
            value,
        ]))
    cookie_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return cookie_path


def _env_cookie_file(dest_dir: Path) -> Optional[Path]:
    cookies = _bili_cookie_dict_from_env()
    if not cookies:
        return None
    return _write_netscape_cookie_file(dest_dir / "_bili_env_cookies.txt", cookies)


def _auto_cookie_browser_sources() -> list[str]:
    configured = str(os.getenv("YTDLP_COOKIES_FROM_BROWSER", "") or "").strip()
    if configured:
        return [configured]
    if not parse_bool(os.getenv("YTDLP_AUTO_COOKIES_FROM_BROWSER", "1"), True):
        return []
    if os.name == "nt":
        return ["edge", "chrome"]
    return ["chrome", "firefox"]


def _yt_dlp_cmd(
    target_url: str,
    output_template: str,
    *,
    cookies_file: Optional[str] = None,
    cookies_from_browser: Optional[str] = None,
    proxy: Optional[str] = None,
    fast_mode: bool = False,
) -> list[str]:
    default_format = (
        "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"
    )
    fast_format = (
        "best[height<=720][ext=mp4]/best[height<=720]/best[ext=mp4]/best"
    )
    format_expr = (
        str(os.getenv("YTDLP_FAST_VIDEO_FORMAT", "") or "").strip() or fast_format
        if fast_mode
        else str(os.getenv("YTDLP_VIDEO_FORMAT", "") or "").strip() or default_format
    )
    cmd = [
        "yt-dlp",
        "--format", format_expr,
        "--merge-output-format", "mp4",
        "--output", output_template,
        "--print-json",
        "--no-playlist",
        "--socket-timeout", "60",
        "--retries", "10",
        "--fragment-retries", "10",
        "--extractor-retries", "5",
        "--retry-sleep", "2",
        "--continue",
        "--http-chunk-size", "10M",
        "--add-header", f"Referer: {_HEADERS['Referer']}",
        "--add-header", f"User-Agent: {_HEADERS['User-Agent']}",
    ]
    if cookies_file:
        cmd += ["--cookies", cookies_file]
    elif cookies_from_browser:
        cmd += ["--cookies-from-browser", cookies_from_browser]
    if proxy:
        cmd += ["--proxy", proxy]
    cmd.append(target_url)
    return cmd


def _format_403_error(error_tail: str) -> str:
    return (
        "yt-dlp 从哔哩哔哩返回了 HTTP 403。\n"
        "可尝试：\n"
        "1) 使用完整视频链接（https://www.bilibili.com/video/BV...）\n"
        "2) 在 Edge/Chrome 登录哔哩哔哩后，设置 YTDLP_COOKIES_FROM_BROWSER=edge|chrome，"
        "或保持自动浏览器 Cookie 回退开启\n"
        "3) 或在 .env 中设置 BILI_SESSDATA，让下载器自动构建 Cookie\n\n"
        f"原始错误：\n{error_tail}"
    )


def _is_browser_cookie_error(error_tail: str) -> bool:
    lower = (error_tail or "").lower()
    tokens = (
        "failed to decrypt with dpapi",
        "could not copy chrome cookie database",
        "could not copy edge cookie database",
        "could not find chrome cookies",
        "could not find edge cookies",
        "browser cookies",
        "database is locked",
        "permission denied",
    )
    return any(token in lower for token in tokens)


def _format_browser_cookie_error(error_tail: str) -> str:
    return (
        "yt-dlp 无法读取本机浏览器 Cookies。\n"
        "通常是 Windows DPAPI 会话不匹配，或浏览器 Cookie 数据库被占用。\n"
        "可尝试：\n"
        "1) 完全关闭 Edge/Chrome 后重试\n"
        "2) 使用拥有浏览器配置文件的同一 Windows 用户运行 worker\n"
        "3) 在 .env 设置 BILI_SESSDATA，后台任务可更稳定鉴权\n"
        "4) 若视频公开可见，可设置 YTDLP_AUTO_COOKIES_FROM_BROWSER=0 跳过浏览器 Cookie 回退\n\n"
        f"原始错误：\n{error_tail}"
    )


def _normalize_bili_url(raw: str) -> str:
    """
    Normalize user input to a usable Bilibili VOD URL.

    Supported inputs:
    - bare BV id: BVxxxxxxxxxx
    - domain without protocol: www.bilibili.com/video/BV...
    """
    s = (raw or "").strip()
    if not s:
        return s

    m = re.fullmatch(r"(BV[a-zA-Z0-9]+)", s)
    if m:
        return f"https://www.bilibili.com/video/{m.group(1)}"

    parsed = urlparse(s)
    if not parsed.scheme and "bilibili.com" in s:
        return f"https://{s.lstrip('/')}"

    return s


def _extract_bvid(url: str) -> Optional[str]:
    m = re.search(r"(BV[a-zA-Z0-9]+)", url)
    return m.group(1) if m else None


def _fetch_video_info(bvid: str, cookies: Optional[dict] = None) -> Optional[dict]:
    """Return Bilibili API data dict for a video."""
    try:
        with httpx.Client(headers=_HEADERS, cookies=cookies or {}, timeout=15) as client:
            resp = client.get(_BILI_VIEW_API, params={"bvid": bvid})
            resp.raise_for_status()
            data = resp.json()
            if data.get("code") == 0:
                return data.get("data")
    except Exception as e:
        console.print(f"[yellow]警告：获取视频信息失败：{e}[/yellow]")
    return None


def _download_danmaku(cid: str | int, dest_dir: Path, title: str) -> Optional[Path]:
    """Download danmaku XML for a video part (cid)."""
    url = _BILI_DANMAKU_URL.format(cid=cid)
    safe_title = re.sub(r"[^\w\-]", "_", title)[:60]
    out_path = dest_dir / f"{safe_title}_danmaku.xml"
    try:
        with httpx.Client(headers=_HEADERS, timeout=30) as client:
            resp = client.get(url)
            resp.raise_for_status()
            out_path.write_bytes(resp.content)
            console.print(f"[green]弹幕已下载 -> {out_path.name}[/green]")
            return out_path
    except Exception as e:
        console.print(f"[yellow]警告：下载弹幕失败：{e}[/yellow]")
    return None


def _download_video(
    url: str,
    dest_dir: Path,
    cookies_file: Optional[str] = None,
    proxy: Optional[str] = None,
) -> Path:
    """Download video with yt-dlp and return local file path."""
    ensure_ytdlp_ready()
    target_url = _normalize_bili_url(url)
    configured_cookie_file = (
        str(cookies_file or "").strip()
        or str(os.getenv("BILI_COOKIES_FILE", "") or "").strip()
        or None
    )
    generated_cookie_file = None
    if configured_cookie_file is None:
        generated_cookie_file = _env_cookie_file(dest_dir)
        if generated_cookie_file is not None:
            configured_cookie_file = str(generated_cookie_file)

    output_template = str(dest_dir / "%(title).60s.%(ext)s")
    attempts: list[tuple[str, Optional[str], Optional[str]]] = []
    seen: set[tuple[str, str]] = set()

    def add_attempt(mode: str, value: Optional[str], label: str) -> None:
        key = (mode, str(value or ""))
        if key in seen:
            return
        seen.add(key)
        attempts.append((mode, value, label))

    if configured_cookie_file:
        label = "cookies file"
        if generated_cookie_file is not None:
            label = "BILI_SESSDATA cookie jar"
        add_attempt("cookie_file", configured_cookie_file, label)
    else:
        add_attempt("none", None, "anonymous request")

    configured_browser = str(os.getenv("YTDLP_COOKIES_FROM_BROWSER", "") or "").strip()
    if configured_browser:
        add_attempt("browser", configured_browser, f"browser cookies ({configured_browser})")
    else:
        for browser in _auto_cookie_browser_sources():
            add_attempt("browser", browser, f"browser cookies ({browser})")

    console.print("[yellow]Downloading video with yt-dlp...[/yellow]")
    timeout_sec = int(os.getenv("WORKER_YTDLP_TIMEOUT_SEC", "900"))
    last_error_tail = ""
    try:
        for mode, value, label in attempts:
            if label:
                console.print(f"[dim]yt-dlp auth attempt: {label}[/dim]")
            timeout_fast_fallback = parse_bool(
                os.getenv("YTDLP_TIMEOUT_FAST_FALLBACK", "1"),
                True,
            )
            result = None
            timeout_error = False
            for fast_mode in (False, True):
                if fast_mode and not timeout_fast_fallback:
                    break
                if fast_mode:
                    console.print("[yellow]下载超时，改用快速格式重试...[/yellow]")
                cmd = _yt_dlp_cmd(
                    target_url,
                    output_template,
                    cookies_file=(value if mode == "cookie_file" else None),
                    cookies_from_browser=(value if mode == "browser" else None),
                    proxy=proxy,
                    fast_mode=fast_mode,
                )
                try:
                    result = subprocess.run(cmd, capture_output=True, timeout=timeout_sec)
                    timeout_error = False
                    break
                except FileNotFoundError:
                    raise RuntimeError("未找到 yt-dlp，请先安装：pip install yt-dlp") from None
                except subprocess.TimeoutExpired:
                    timeout_error = True
                    continue

            if timeout_error or result is None:
                raise RuntimeError(
                    "yt-dlp 下载哔哩哔哩视频超时。"
                    "请尝试更短视频、更稳定网络，或增大 WORKER_YTDLP_TIMEOUT_SEC。"
                ) from None

            stdout_text = safe_decode(result.stdout)
            stderr_text = safe_decode(result.stderr)
            last_error_tail = stderr_text[-2000:]

            if result.returncode == 0:
                for line in reversed(stdout_text.splitlines()):
                    line = line.strip()
                    if line.startswith("{"):
                        try:
                            info = json.loads(line)
                            filename = info.get("filename") or info.get("_filename")
                            if filename and Path(filename).exists():
                                return Path(filename)
                        except json.JSONDecodeError:
                            pass

                mp4s = sorted(dest_dir.glob("*.mp4"), key=os.path.getmtime, reverse=True)
                if mp4s:
                    return mp4s[0]
                raise RuntimeError("yt-dlp 已执行完成，但未找到输出文件。")

            should_try_next = "403" in last_error_tail or "Forbidden" in last_error_tail
            if mode == "browser" and _is_browser_cookie_error(last_error_tail):
                should_try_next = True
            if should_try_next and (mode, value, label) != attempts[-1]:
                continue

            if mode == "browser" and _is_browser_cookie_error(last_error_tail):
                raise RuntimeError(_format_browser_cookie_error(last_error_tail))
            if "403" in last_error_tail or "Forbidden" in last_error_tail:
                raise RuntimeError(_format_403_error(last_error_tail))
            raise RuntimeError(f"yt-dlp 执行失败：\n{last_error_tail}")

        raise RuntimeError(_format_403_error(last_error_tail or "哔哩哔哩拒绝了所有下载尝试。"))
    finally:
        if generated_cookie_file is not None:
            generated_cookie_file.unlink(missing_ok=True)


class BiliVodIngest:
    """
    Download a Bilibili VOD and its danmaku.

    Args:
        url:          Bilibili video URL.
        work_dir:     Directory for downloaded files (temp dir if None).
        cookies_file: Path to a Netscape-format cookies.txt.
        sessdata:     SESSDATA cookie value.
    """

    def __init__(
        self,
        url: str,
        work_dir: Optional[str] = None,
        cookies_file: Optional[str] = None,
        sessdata: Optional[str] = None,
        proxy: Optional[str] = None,
        progress_cb: Optional[Callable[[float], None]] = None,
    ):
        self.url = _normalize_bili_url(url)
        self.work_dir = Path(work_dir) if work_dir else None
        self.cookies_file = cookies_file
        self.sessdata = sessdata
        self.proxy = proxy
        self.progress_cb = progress_cb

    def fetch_danmaku(self, url: Optional[str] = None) -> list[DanmakuComment]:
        """Fetch danmaku comments only, without downloading video."""
        target_url = _normalize_bili_url((url or self.url).strip())
        if not target_url:
            raise ValueError("抓取弹幕需要提供哔哩哔哩视频链接")

        bvid = _extract_bvid(target_url)
        if not bvid:
            return []

        cookies = {}
        if self.sessdata:
            cookies["SESSDATA"] = self.sessdata

        info = _fetch_video_info(bvid, cookies)
        if not info:
            return []

        cid = info.get("cid")
        title = info.get("title", bvid)
        if not cid:
            return []

        temp_dir: Optional[str] = None
        if self.work_dir:
            self.work_dir.mkdir(parents=True, exist_ok=True)
            dest_dir = self.work_dir
        else:
            temp_dir = tempfile.mkdtemp(prefix="stream_clipper_dm_")
            dest_dir = Path(temp_dir)

        try:
            xml_path = _download_danmaku(cid, dest_dir, title)
            if not xml_path:
                return []
            return parse_xml(str(xml_path))
        finally:
            if temp_dir:
                try:
                    for p in dest_dir.iterdir():
                        p.unlink(missing_ok=True)
                    dest_dir.rmdir()
                except Exception:
                    pass

    def run(self) -> IngestResult:
        if self.work_dir:
            self.work_dir.mkdir(parents=True, exist_ok=True)
            dest_dir = self.work_dir
            is_temp = False
        else:
            dest_dir = Path(tempfile.mkdtemp(prefix="stream_clipper_"))
            is_temp = True

        danmaku_future = None
        with ThreadPoolExecutor(max_workers=1) as ex:
            danmaku_future = ex.submit(self.fetch_danmaku, self.url)

            if self.progress_cb is not None:
                try:
                    self.progress_cb(0.22)
                except Exception:
                    pass
            video_path = _download_video(self.url, dest_dir, self.cookies_file, self.proxy)
        console.print(f"[green]Video saved -> {video_path.name}[/green]")
        if self.progress_cb is not None:
            try:
                self.progress_cb(0.30)
            except Exception:
                pass

        cookies = {}
        if self.sessdata:
            cookies["SESSDATA"] = self.sessdata

        title = video_path.stem
        bvid = _extract_bvid(self.url)
        if bvid:
            info = _fetch_video_info(bvid, cookies)
            if info:
                title = info.get("title", title)

        danmaku_comments = []
        try:
            if danmaku_future is not None:
                danmaku_comments = danmaku_future.result(timeout=120)
        except Exception:
            danmaku_comments = self.fetch_danmaku(self.url)
        if danmaku_comments:
            console.print(f"[green]Loaded {len(danmaku_comments)} danmaku comments[/green]")
        if self.progress_cb is not None:
            try:
                self.progress_cb(0.38)
            except Exception:
                pass

        duration = _probe_duration(video_path)

        return IngestResult(
            video_path=video_path,
            comments=danmaku_comments,
            duration=duration,
            title=title,
            source_url=self.url,
            is_temp=is_temp,
        )
