"""
Generic web video/live ingest powered by yt-dlp.

This module is intentionally platform-agnostic and is used for
non-Bilibili sources (e.g. YouTube, Douyin, Xigua, Weibo, Xiaohongshu).
"""

from __future__ import annotations

import json
import os
import re
import signal
import subprocess
import tempfile
import time
import httpx
from pathlib import Path
from typing import Callable, Optional
from urllib.parse import parse_qs, urlparse

from ..logging import console
from ..utils import parse_bool, safe_decode
from .base import IngestResult
from .local import _probe_duration
from .ytdlp_guard import ensure_ytdlp_ready

_MIN_RECORD_BYTES = 256 * 1024
_BROWSER_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/124.0.0.0 Safari/537.36"
)


def normalize_web_url(raw: str) -> str:
    text = str(raw or "").strip()
    if not text:
        return text
    parsed = urlparse(text)
    if parsed.scheme in {"http", "https"}:
        return text
    if re.search(r"[A-Za-z0-9.-]+\.[A-Za-z]{2,}", text):
        return f"https://{text.lstrip('/')}"
    return text


def _candidate_web_urls(raw: str) -> list[str]:
    """
    Build candidate URLs for yt-dlp when users paste non-canonical pages.

    Example:
      https://www.douyin.com/jingxuan?modal_id=123456
      -> https://www.douyin.com/video/123456
    """
    base = normalize_web_url(raw)
    if not base:
        return []

    out: list[str] = []
    seen: set[str] = set()

    def add(url: str) -> None:
        text = str(url or "").strip()
        if not text or text in seen:
            return
        seen.add(text)
        out.append(text)

    add(base)
    parsed = urlparse(base)
    host = parsed.netloc.lower()

    if host.endswith("douyin.com"):
        modal_id = (parse_qs(parsed.query).get("modal_id") or [None])[0]
        if modal_id and re.fullmatch(r"\d{8,32}", str(modal_id)):
            add(f"https://www.douyin.com/video/{modal_id}")

    return out


def _configured_web_cookies_file(explicit: Optional[str] = None) -> Optional[str]:
    return (
        str(explicit or "").strip()
        or str(os.getenv("WEB_COOKIES_FILE", "") or "").strip()
        or str(os.getenv("YTDLP_COOKIES_FILE", "") or "").strip()
        or None
    )


def _write_netscape_cookie_file(cookie_path: Path, cookies: list[tuple[str, str, str]]) -> Path:
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by Stream Clipper web ingest fallback.",
    ]
    for domain, name, value in cookies:
        d = str(domain or "").strip()
        n = str(name or "").strip()
        v = str(value or "").strip()
        if not d or not n or not v:
            continue
        lines.append("\t".join([d, "TRUE", "/", "TRUE", "2147483647", n, v]))
    cookie_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return cookie_path


def _bootstrap_session_cookie_file(target_url: str, dest_dir: Path) -> Optional[Path]:
    """
    For anti-bot pages (notably Douyin), fetch the page once to obtain
    short-lived web cookies and pass them to yt-dlp as a first attempt.
    """
    parsed = urlparse(target_url)
    host = parsed.netloc.lower()
    if not host.endswith("douyin.com"):
        return None

    headers = {
        "User-Agent": _BROWSER_UA,
        "Referer": "https://www.douyin.com/",
    }
    try:
        with httpx.Client(headers=headers, follow_redirects=True, timeout=15) as client:
            client.get(target_url)
            collected: list[tuple[str, str, str]] = []
            for c in client.cookies.jar:
                domain = str(getattr(c, "domain", "") or "").strip()
                if not domain:
                    domain = ".douyin.com"
                if "douyin.com" not in domain:
                    continue
                name = str(getattr(c, "name", "") or "").strip()
                value = str(getattr(c, "value", "") or "").strip()
                if name and value:
                    if not domain.startswith("."):
                        domain = f".{domain}"
                    collected.append((domain, name, value))
            if not collected:
                return None
            return _write_netscape_cookie_file(dest_dir / "_web_bootstrap_cookies.txt", collected)
    except Exception:
        return None


def _auto_cookie_browser_sources() -> list[str]:
    configured = (
        str(os.getenv("WEB_COOKIES_FROM_BROWSER", "") or "").strip()
        or str(os.getenv("YTDLP_WEB_COOKIES_FROM_BROWSER", "") or "").strip()
        or str(os.getenv("YTDLP_COOKIES_FROM_BROWSER", "") or "").strip()
    )
    if configured:
        return [configured]
    auto_enabled = parse_bool(
        os.getenv(
            "WEB_AUTO_COOKIES_FROM_BROWSER",
            os.getenv("YTDLP_WEB_AUTO_COOKIES_FROM_BROWSER", "1"),
        ),
        True,
    )
    if not auto_enabled:
        return []
    if os.name == "nt":
        return ["edge", "chrome"]
    return ["chrome", "firefox"]


def _yt_dlp_cmd(
    target_url: str,
    output_template: str,
    *,
    proxy: Optional[str] = None,
    cookies_file: Optional[str] = None,
    cookies_from_browser: Optional[str] = None,
    headers: Optional[dict[str, str]] = None,
    fast_mode: bool = False,
) -> list[str]:
    default_format = (
        "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"
    )
    fast_format = (
        "best[height<=720][ext=mp4]/best[height<=720]/best[ext=mp4]/best"
    )
    format_expr = (
        str(os.getenv("YTDLP_FAST_VIDEO_FORMAT", "") or "").strip() or fast_format
        if fast_mode
        else str(os.getenv("YTDLP_VIDEO_FORMAT", "") or "").strip() or default_format
    )
    cmd = [
        "yt-dlp",
        "--format", format_expr,
        "--merge-output-format", "mp4",
        "--output", output_template,
        "--print-json",
        "--no-playlist",
        "--socket-timeout", "60",
        "--retries", "10",
        "--fragment-retries", "10",
        "--extractor-retries", "5",
        "--retry-sleep", "2",
        "--continue",
        "--http-chunk-size", "10M",
    ]
    if cookies_file:
        cmd += ["--cookies", cookies_file]
    elif cookies_from_browser:
        cmd += ["--cookies-from-browser", cookies_from_browser]
    if headers:
        for k, v in headers.items():
            if str(k).strip() and str(v).strip():
                cmd += ["--add-header", f"{k}: {v}"]
    if proxy:
        cmd += ["--proxy", proxy]
    cmd.append(target_url)
    return cmd


def _target_headers(target_url: str) -> dict[str, str]:
    parsed = urlparse(target_url)
    host = parsed.netloc.lower()
    out = {"User-Agent": _BROWSER_UA}
    if host.endswith("douyin.com"):
        out["Referer"] = "https://www.douyin.com/"
    return out


def _is_browser_cookie_error(error_tail: str) -> bool:
    lower = (error_tail or "").lower()
    tokens = (
        "failed to decrypt with dpapi",
        "could not copy chrome cookie database",
        "could not copy edge cookie database",
        "could not find chrome cookies",
        "could not find edge cookies",
        "browser cookies",
        "database is locked",
        "permission denied",
    )
    return any(token in lower for token in tokens)


def _needs_fresh_cookies(error_tail: str) -> bool:
    lower = (error_tail or "").lower()
    return "fresh cookies" in lower and "needed" in lower


def _format_fresh_cookies_error(error_tail: str) -> str:
    return (
        "该来源需要可用的浏览器最新 Cookies 才能让 yt-dlp 下载。\n"
        "可尝试：\n"
        "1) 先在 Edge/Chrome 打开目标页面，再立即重试\n"
        "2) 设置 WEB_COOKIES_FROM_BROWSER=edge（或 chrome）\n"
        "3) 或导出 cookies.txt，并设置 WEB_COOKIES_FILE=/path/to/cookies.txt\n"
        "4) 确保 worker 与浏览器配置文件属于同一系统用户\n\n"
        f"原始错误：\n{error_tail}"
    )


def _format_browser_cookie_error(error_tail: str) -> str:
    return (
        "yt-dlp 无法读取本机浏览器 Cookies。\n"
        "常见原因是 Windows DPAPI 会话不匹配，或浏览器 Cookie 数据库被占用。\n"
        "可尝试：\n"
        "1) 完全关闭 Edge/Chrome 后重试\n"
        "2) 使用与浏览器配置文件相同的 Windows 用户运行 worker\n"
        "3) 提供导出的 cookies.txt，并设置 WEB_COOKIES_FILE\n\n"
        f"原始错误：\n{error_tail}"
    )


def _resolve_downloaded_output(dest_dir: Path) -> Optional[Path]:
    media_exts = {".mp4", ".mkv", ".webm", ".mov", ".flv", ".ts", ".m4v"}
    candidates = []
    for p in dest_dir.glob("*"):
        if not p.is_file():
            continue
        if p.suffix.lower() in {".part", ".ytdl", ".tmp", ".log"}:
            continue
        if p.suffix.lower() in media_exts:
            candidates.append(p)
    if not candidates:
        return None
    return max(candidates, key=lambda p: p.stat().st_mtime if p.exists() else 0.0)


def download_video(
    url: str,
    dest_dir: Path,
    *,
    proxy: Optional[str] = None,
    cookies_file: Optional[str] = None,
    timeout_sec: int = 900,
) -> Path:
    ensure_ytdlp_ready()
    dest_dir.mkdir(parents=True, exist_ok=True)
    output_template = str(dest_dir / "%(title).60s.%(ext)s")
    candidates = _candidate_web_urls(url)
    if not candidates:
        raise RuntimeError("来源 URL 为空或格式无效。")

    configured_cookie_file = _configured_web_cookies_file(cookies_file)
    attempts: list[tuple[str, Optional[str], str]] = []
    seen: set[tuple[str, str]] = set()

    def add_attempt(mode: str, value: Optional[str], label: str) -> None:
        key = (mode, str(value or ""))
        if key in seen:
            return
        seen.add(key)
        attempts.append((mode, value, label))

    generated_cookie_files: list[Path] = []

    if configured_cookie_file:
        add_attempt("cookie_file", configured_cookie_file, "cookies file")
    for browser in _auto_cookie_browser_sources():
        add_attempt("browser", browser, f"browser cookies ({browser})")
    add_attempt("none", None, "anonymous request")

    last_error_tail = ""
    saw_browser_cookie_error = False
    for target_url in candidates:
        bootstrap_cookie_file = _bootstrap_session_cookie_file(target_url, dest_dir)
        target_attempts = attempts
        if bootstrap_cookie_file is not None:
            generated_cookie_files.append(bootstrap_cookie_file)
            target_attempts = [
                ("cookie_file", str(bootstrap_cookie_file), "bootstrap web cookies"),
                *attempts,
            ]
        unsupported_for_this_url = False
        headers = _target_headers(target_url)
        for mode, value, _label in target_attempts:
            cmd = _yt_dlp_cmd(
                target_url,
                output_template,
                proxy=proxy,
                cookies_file=(value if mode == "cookie_file" else None),
                cookies_from_browser=(value if mode == "browser" else None),
                headers=headers,
            )
            try:
                result = subprocess.run(cmd, capture_output=True, timeout=timeout_sec)
            except FileNotFoundError:
                raise RuntimeError("未找到 yt-dlp，请先安装：pip install yt-dlp") from None
            except subprocess.TimeoutExpired:
                raise RuntimeError(
                    "yt-dlp 下载来源视频超时。"
                    "请尝试更短视频、更稳定网络，或增大 WORKER_YTDLP_TIMEOUT_SEC。"
                ) from None

            stdout_text = safe_decode(result.stdout)
            stderr_text = safe_decode(result.stderr)
            last_error_tail = stderr_text[-2000:]
            if result.returncode != 0:
                lower_err = stderr_text.lower()
                if "unsupported url" in lower_err:
                    unsupported_for_this_url = True
                    break
                if mode == "browser" and _is_browser_cookie_error(last_error_tail):
                    saw_browser_cookie_error = True
                    continue
                if _needs_fresh_cookies(last_error_tail):
                    continue
                continue

            for line in reversed(stdout_text.splitlines()):
                line = line.strip()
                if not line.startswith("{"):
                    continue
                try:
                    data = json.loads(line)
                except json.JSONDecodeError:
                    continue
                filename = data.get("filename") or data.get("_filename")
                if filename and Path(filename).exists():
                    return Path(filename)

            resolved = _resolve_downloaded_output(dest_dir)
            if resolved:
                return resolved
            last_error_tail = "yt-dlp 已执行完成，但未找到输出文件。"
            break
        if unsupported_for_this_url and target_url != candidates[-1]:
            continue

    try:
        lower = last_error_tail.lower()
        if _needs_fresh_cookies(last_error_tail):
            raise RuntimeError(_format_fresh_cookies_error(last_error_tail))
        if saw_browser_cookie_error and _is_browser_cookie_error(last_error_tail):
            raise RuntimeError(_format_browser_cookie_error(last_error_tail))
        if "unsupported url" in lower and "douyin.com" in str(url).lower():
            raise RuntimeError(
                "yt-dlp 不支持该抖音页面链接的直接解析。\n"
                "请改用视频直链（优先 /video/<id> 或 v.douyin.com 短链）。\n\n"
                f"原始错误：\n{last_error_tail}"
            )
        raise RuntimeError(f"yt-dlp 执行失败：\n{last_error_tail}")
    finally:
        for p in generated_cookie_files:
            try:
                p.unlink(missing_ok=True)
            except Exception:
                pass


def _start_live_recording(
    url: str,
    output_stem: Path,
    *,
    proxy: Optional[str] = None,
) -> tuple[subprocess.Popen, Path, Path]:
    ensure_ytdlp_ready()
    stdout_log = output_stem.with_suffix(".yt-dlp.stdout.log")
    stderr_log = output_stem.with_suffix(".yt-dlp.stderr.log")
    output_tmpl = f"{output_stem}.%(ext)s"
    cmd = [
        "yt-dlp",
        "--compat-options", "allow-unsafe-ext",
        "--output", output_tmpl,
        "--merge-output-format", "mp4",
        "--no-part",
        "--hls-use-mpegts",
        "--socket-timeout", "30",
        "--retries", "5",
        "--fragment-retries", "5",
        "--concurrent-fragments", "3",
    ]
    if proxy:
        cmd += ["--proxy", proxy]
    cmd.append(normalize_web_url(url))

    with stdout_log.open("wb") as out_f, stderr_log.open("wb") as err_f:
        try:
            kwargs = {
                "stdout": out_f,
                "stderr": err_f,
                "stdin": subprocess.PIPE,
            }
            if os.name == "nt":
                kwargs["creationflags"] = subprocess.CREATE_NEW_PROCESS_GROUP
            process = subprocess.Popen(cmd, **kwargs)
        except FileNotFoundError:
            raise RuntimeError("未找到 yt-dlp，请先安装：pip install yt-dlp") from None
    return process, stdout_log, stderr_log


def _resolve_live_output(output_stem: Path) -> Optional[Path]:
    preferred_exts = {".mp4", ".mkv", ".flv", ".ts", ".webm"}
    candidates = []
    for p in output_stem.parent.glob(f"{output_stem.name}*"):
        if not p.is_file():
            continue
        if p.name.endswith(".yt-dlp.stdout.log") or p.name.endswith(".yt-dlp.stderr.log"):
            continue
        if p.suffix.lower() in {".part", ".ytdl"}:
            continue
        candidates.append(p)
    if not candidates:
        return None

    def sort_key(path: Path) -> tuple[int, int]:
        ext_pref = 1 if path.suffix.lower() in preferred_exts else 0
        size = path.stat().st_size if path.exists() else 0
        return ext_pref, size

    return max(candidates, key=sort_key)


def _graceful_stop_recorder(recorder: subprocess.Popen) -> None:
    if recorder.poll() is not None:
        return

    gracefully_stopped = False
    try:
        if os.name == "nt":
            recorder.send_signal(signal.CTRL_BREAK_EVENT)
        else:
            recorder.send_signal(signal.SIGINT)
        recorder.wait(timeout=12)
        gracefully_stopped = True
    except Exception:
        gracefully_stopped = False

    if not gracefully_stopped and recorder.poll() is None:
        recorder.terminate()
        try:
            recorder.wait(timeout=5)
        except subprocess.TimeoutExpired:
            recorder.kill()


class WebVodIngest:
    def __init__(
        self,
        url: str,
        work_dir: Optional[str] = None,
        proxy: Optional[str] = None,
        progress_cb: Optional[Callable[[float], None]] = None,
    ):
        self.url = normalize_web_url(url)
        self.work_dir = Path(work_dir) if work_dir else None
        self.proxy = proxy
        self.progress_cb = progress_cb

    def run(self) -> IngestResult:
        if self.work_dir:
            self.work_dir.mkdir(parents=True, exist_ok=True)
            dest_dir = self.work_dir
            is_temp = False
        else:
            dest_dir = Path(tempfile.mkdtemp(prefix="stream_clipper_web_"))
            is_temp = True

        if self.progress_cb is not None:
            try:
                self.progress_cb(0.22)
            except Exception:
                pass

        video_path = download_video(self.url, dest_dir, proxy=self.proxy)
        duration = _probe_duration(video_path)

        if self.progress_cb is not None:
            try:
                self.progress_cb(0.38)
            except Exception:
                pass

        return IngestResult(
            video_path=video_path,
            comments=[],
            duration=duration,
            title=video_path.stem,
            source_url=self.url,
            is_temp=is_temp,
        )


class WebLiveIngest:
    def __init__(
        self,
        url: str,
        work_dir: Optional[str] = None,
        max_seconds: int = 1800,
        proxy: Optional[str] = None,
        progress_cb: Optional[Callable[[float, int], None]] = None,
    ):
        self.url = normalize_web_url(url)
        self.work_dir = Path(work_dir) if work_dir else None
        self.max_seconds = max(0, int(max_seconds))
        self.proxy = proxy
        self.progress_cb = progress_cb

    def run(self) -> IngestResult:
        if not self.url:
            raise ValueError("直播录制必须提供链接")

        if self.work_dir:
            self.work_dir.mkdir(parents=True, exist_ok=True)
            dest_dir = self.work_dir
            is_temp = False
        else:
            dest_dir = Path(tempfile.mkdtemp(prefix="stream_clipper_live_web_"))
            is_temp = True

        ts = time.strftime("%Y%m%d_%H%M%S")
        output_stem = dest_dir / f"web_live_{ts}"
        recorder, _stdout_log, stderr_log = _start_live_recording(
            self.url,
            output_stem,
            proxy=self.proxy,
        )
        start_time = time.monotonic()
        console.print(
            "[bold green]直播录制已开始。[/bold green] "
            + (f"（将在 {self.max_seconds} 秒后自动停止）" if self.max_seconds else "")
        )
        try:
            while True:
                elapsed = time.monotonic() - start_time
                if self.progress_cb is not None:
                    try:
                        self.progress_cb(elapsed, 0)
                    except Exception:
                        pass
                if self.max_seconds and elapsed >= self.max_seconds:
                    break
                if recorder.poll() is not None:
                    break
                time.sleep(0.5)
        finally:
            _graceful_stop_recorder(recorder)

        output_path = _resolve_live_output(output_stem)
        recorded_bytes = output_path.stat().st_size if output_path and output_path.exists() else 0
        if output_path is None or recorded_bytes < _MIN_RECORD_BYTES:
            stderr_tail = ""
            if stderr_log.exists():
                stderr_tail = safe_decode(stderr_log.read_bytes())[-1200:].strip()
            found_files = [str(p.name) for p in output_stem.parent.glob(f"{output_stem.name}*")]
            raise RuntimeError(
                f"录制文件缺失或体积过小：{output_path or '(none)'}\n"
                f"录制字节数：{recorded_bytes}\n"
                f"匹配到的文件：{found_files}\n"
                f"yt-dlp 错误尾部：\n{stderr_tail or '(empty)'}"
            )

        duration = _probe_duration(output_path)
        return IngestResult(
            video_path=output_path,
            comments=[],
            duration=duration,
            title=output_path.stem,
            source_url=self.url,
            is_temp=is_temp,
        )
